# Generated by Django 3.2 on 2022-09-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='wifi',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
