# Generated by Django 3.2 on 2022-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu_api', '0002_business_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
