# Generated by Django 3.2 on 2022-09-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu_api', '0004_alter_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_fitting',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
