# Generated by Django 3.2 on 2022-09-23 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emenu_api', '0006_alter_seat_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='emenu_api.business'),
        ),
    ]
