# Generated by Django 3.2 on 2022-09-26 14:48

from django.db import migrations, models
import django.db.models.deletion
import emenu_api.image_path_gen_utility


class Migration(migrations.Migration):

    dependencies = [
        ('emenu_api', '0007_alter_seat_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=emenu_api.image_path_gen_utility.CategoryImageGenerator())),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=emenu_api.image_path_gen_utility.BusinessImageGenerator()),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('recipes', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=emenu_api.image_path_gen_utility.ItemImageGenerator())),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='emenu_api.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='emenu_api.business'),
        ),
    ]
