const SET_AUTH_USER = 'SET_AUTH_USER';
const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
const SET_ITEMS = 'SET_ITEMS';

export default {
    SET_AUTH_USER,
    SET_AUTH_LOADING,
    SET_AUTHENTICATED,
    SET_ITEMS
}